# Generated by Django 6.0.3 on 2026-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herooverview',
            name='calling_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='slider/'),
        ),
    ]
