# Generated by Django 6.0.3 on 2026-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herooverview_calling_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herooverview',
            name='calling_photo',
            field=models.ImageField(blank=True, upload_to='slider/'),
        ),
    ]
