# Generated by Django 6.0.3 on 2026-03-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_herooverview_calling_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='herooverview',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
