# Generated by Django 6.0.3 on 2026-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_faq_order_alter_herooverview_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('message_from', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='message/')),
                ('message', models.TextField()),
                ('message_optional', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords (e.g. hospital, doctor)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='working_hour',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
