# Generated by Django 6.0.3 on 2026-04-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, default='img/user-icon.png', upload_to='blood_donors/')),
                ('last_donated', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
