# Generated by Django 6.0.3 on 2026-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blood_donors/'),
        ),
    ]
