# Generated by Django 6.0.3 on 2026-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='about_us/')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('short_message', models.TextField()),
                ('video_url', models.URLField(blank=True, default='https://')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
