# Generated by Django 6.0.3 on 2026-03-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_department_department_icon_alter_department_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField()),
                ('services', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
