# Generated by Django 6.0.3 on 2026-03-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='services',
            new_name='service',
        ),
    ]
