# Generated by Django 6.0.3 on 2026-03-23 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('cover_photo', models.ImageField(upload_to='blogs/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('gallery_title', models.CharField(blank=True, max_length=150)),
                ('gallery_image_01', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('gallery_image_02', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('gallery_image_03', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('highlight_title', models.CharField(blank=True, max_length=150)),
                ('key_point_01', models.CharField(blank=True, max_length=100)),
                ('key_point_02', models.CharField(blank=True, max_length=100)),
                ('key_point_03', models.CharField(blank=True, max_length=100)),
                ('key_point_04', models.CharField(blank=True, max_length=100)),
                ('key_point_05', models.CharField(blank=True, max_length=100)),
                ('key_point_06', models.CharField(blank=True, max_length=100)),
                ('key_point_07', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('paragraph_01', models.TextField(blank=True)),
                ('paragraph_02', models.TextField(blank=True)),
                ('paragraph_03', models.TextField(blank=True)),
                ('paragraph_04', models.TextField(blank=True)),
                ('paragraph_05', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
