# Generated by Django 6.0.3 on 2026-04-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='department',
        ),
    ]
