# Generated by Django 6.0.3 on 2026-06-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='is_7days',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='doctor.specialization'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Saturday', 'শনিবার'), ('Sunday', 'রবিবার'), ('Monday', 'সোমবার'), ('Tuesday', 'মঙ্গলবার'), ('Wednesday', 'বুধবার'), ('Thursday', 'বৃহস্পতিবার'), ('Friday', 'শুক্রবার')], max_length=10, null=True),
        ),
    ]
